/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    ForecastData: typeof import('../components/Forecast/ForecastData.vue')['default']
    ForecastList: typeof import('../components/Forecast/ForecastList.vue')['default']
    Icon: typeof import('../components/Base/Icon.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LanguageSwitcher: typeof import('../components/Layout/LanguageSwitcher.vue')['default']
    MatchData: typeof import('../components/Match/MatchData.vue')['default']
    MatchDialog: typeof import('../components/Match/MatchDialog.vue')['default']
    MatchItem: typeof import('../components/Match/MatchItem.vue')['default']
    MobileTabs: typeof import('../components/Layout/MobileTabs.vue')['default']
    NavBar: typeof import('../components/Layout/NavBar.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreDisplay: typeof import('../components/Forecast/ScoreDisplay.vue')['default']
    ScoreForecast: typeof import('../components/Forecast/ScoreForecast.vue')['default']
    Select: typeof import('primevue/select')['default']
    SeriesSelector: typeof import('../components/Layout/SeriesSelector.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    TeamLogo: typeof import('../components/Team/TeamLogo.vue')['default']
    ThemeSwitcher: typeof import('../components/Layout/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UserMenu: typeof import('../components/Layout/UserMenu.vue')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
